# Generated by Django 5.1.1 on 2025-05-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.IntegerField(),
        ),
    ]
