# Generated by Django 5.1.1 on 2024-09-29 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
        migrations.AddField(
            model_name='film',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='films_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.CharField(choices=[('Dramat', 'Drama'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Komedia', 'Comedy')], default='Dramat', max_length=8),
        ),
        migrations.AddField(
            model_name='film',
            name='want_to_watch',
            field=models.ManyToManyField(blank=True, null=True, related_name='films_to_watch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='watched',
            field=models.ManyToManyField(blank=True, null=True, related_name='films_watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
