# Generated by Django 5.1.1 on 2024-09-29 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_remove_film_rating_film_added_by_film_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='want_to_watch',
            field=models.ManyToManyField(blank=True, related_name='films_to_watch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='film',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='films_watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
